version: '3'

services:
  message_queue:
    image: oleandertwig/message_queue
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
      - 5673:5673
